-- Generated by spritter v0.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["file_count"] = 1,
  ["height"] = 256,
  ["line_length"] = 7,
  ["lines_per_file"] = 32,
  ["name"] = "tmp",
  ["scale"] = 0.5,
  ["shift"] = {x = 2 / 64, y = 0 / 64},
  ["sprite_count"] = 30,
  ["width"] = 166,
}
