-- Generated by spritter v0.8.1 - https://github.com/fgardt/factorio-spritter
return {
    ["file_count"] = 1,
    ["height"] = 117,
    ["line_length"] = 1,
    ["lines_per_file"] = 70,
    ["name"] = "tmp",
    ["scale"] = 0.5,
    ["shift"] = {x = 2.5 / 64, y = 69.5 / 64},
    ["sprite_count"] = 1,
    ["width"] = 219,
  }
  